### ISSUE TITLE
Parameter subscription not working

### ISSUE THREAD

**Issue by taguan** [yamcs/yamcs-python#7]
Hello,

I have written the following Python code:

```
from time import sleep

from yamcs.client import YamcsClient

client = YamcsClient('host.docker.internal:8090')
processor = client.get_processor(instance='pnext', processor='realtime')

found = False


def wait_for_stype_9(data):
    print(data)
    for parameter in data.parameters:
        print(parameter)
        if parameter == 9:
            global found
            found = True


processor.create_parameter_subscription('/PNEXT/pus_service_type',
                                        on_data=wait_for_stype_9)
while not found:
    sleep(1)
```

If I wrote my code correctly, I should have at least something printed every time the parameter /PNEXT/pus_service_type is updated.
When running the script, nothing is printed (forever).

Looking at the yamcs web interface, I can see that many values are received for this parameter (one every time I receive a packet in realtime).

Any idea?

**Comment by fqqb** [comment]
Hi, which version of python is this? And is this with a recent yamcs-client library?

Does a simple call like this work? :

```
from yamcs.client import YamcsClient
client = YamcsClient('host.docker.internal:8090')
print(client.get_time('pnext'))
```

I remember we used to have problems in the past with exceptions in callbacks that were not getting printed, but that should have been fixed a while ago by wrapping all callbacks with a try/except clause (https://github.com/yamcs/yamcs-python/commit/0a8dfc4a53423de505e832defd5b86342d6c91a9).

If none of this helps, is there any clue in the Yamcs server log?

**Comment by taguan** [comment]
Hello,

Python version: 3.7.2
Yamcs-client: 1.4.6

The script you gave me works: 2020-05-07 07:13:49.568000
I have written quite a few scripts, all working (sending command, reading a parameter, reading a packet...) Only the one I report in this ticket doesn't work.

The try-catch structure of the commit you have linked seems present in the code I execute.

Here are the logs from yamcs:

yamcs_1  | May 07 07:19:40.082 _global [19] org.yamcs.http.HttpServer [FINE] [id: 0xf58ce822, L:/0.0.0.0:8090] READ: [id: 0xe084abf8, L:/172.20.0.2:8090 - R:/172.20.0.1:54860]
yamcs_1  | May 07 07:19:40.082 _global [19] org.yamcs.http.HttpServer [FINE] [id: 0xf58ce822, L:/0.0.0.0:8090] READ COMPLETE
yamcs_1  | May 07 07:19:40.087 _global [26] org.yamcs.http.HttpRequestHandler [FINE] e084abf8 GET /_websocket/pnext/realtime
yamcs_1  | May 07 07:19:40.092 _global [26] org.yamcs.http.websocket.WebSocketFrameHandler [INFO] GET /_websocket/pnext/realtime 101 [subprotocol: protobuf]
yamcs_1  | May 07 07:19:40.095 _global [26] org.yamcs.http.websocket.WebSocketFrameHandler [FINE] Received frame BinaryWebSocketFrame(data: PooledUnsafeDirectByteBuf(ridx: 0, widx: 72, cap: 72))
yamcs_1  | May 07 07:19:40.095 pnext [26] org.yamcs.parameter.ParameterRequestManager[realtime] [FINE] new request with subscriptionId 10 with 1 items


In my opinion everything looks fine, apart that the subscription doesn't receive any item. But in the web GUI I can effectively see new values for that parameters coming in in realtime, so there is something weird.

**Comment by fqqb** [comment]
Your script and log look OK to me too, so this may take a few more iterations.

Do you get output from this:

```
print(processor.get_parameter_value("/PNEXT/pus_service_type", from_cache=False, timeout=10))
```

I would also like to test the possibility of this being a WebSocket issue. Does a script like this work:

```
from yamcs.client import YamcsClient
client = YamcsClient("host.docker.internal:8090")
def cb(data):
    print(data)

client.create_time_subscription("pnext", on_data=cb)
sleep(5)
```

**Comment by taguan** [comment]
OK, I found the issue!
Trying to run your second script, it worked but I noticed that data was printed only after 5 seconds in bulk.
My script was never finishing, because I had to make the comparison on parameter.eng_value and not on parameter

Combination of the two: nothing was ever printed.

In fact, just adding "flush=True" to my print statement allows logs to be printed in realtime:
print(parameter.eng_value, flush=True)

Thanks a lot for the support, it helped me understanding what was wrong. There is actually no bug in Yamcs or in the Python API.
I might just suggest updating the docs where you show example of code with subscriptions, adding "flush=True" to the print methods. That might save future users similar concerns that I had.

**Comment by fqqb** [comment]
I guess that's this PYTHONUNBUFFERED thing, i'll investigate it. I do not have those delays on my setup.

Glad you solved it anyway. From your script it also looks like we should perhaps also add some easier (blocking) API for waiting on specific TM conditions. I'll try to come up with something for a next release.
